name: LTC PRO (Puerto 80)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, pro]
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias (PHPMailer)
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction

      - name: Asegurar directorios de carga
        run: |
          mkdir -p public/uploads
          chmod -R 775 public/uploads
          sudo chown -R $USER:www-data public/uploads

      - name: Asegurar permisos de grupo
        run: chmod -R 775 .